[project]
name = "curso-agno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.7.11",
    "groq>=0.31.0",
    "python-dotenv>=1.1.1",
    "tavily-python>=0.7.11",
    "yfinance>=0.2.65",
]
